Bike_Sharing_D4/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
import home.urls as home
import voucher.urls as voucher
import acara.urls as acara
import penugasan.urls as penugasan
import peminjaman.urls as rent
import sepeda.urls as sepeda
import stasiun.urls as stasiun

import account.urls as account
import transaksi.urls as transaksi
import laporan.urls as laporan



import transaksi.urls as transaksi
from home import views
from voucher import views
from penugasan import views
from acara import views
from peminjaman import views
from sepeda import views
from stasiun import views
from account import views
from transaksi import views
from laporan import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(home)),
    path('', include(voucher, namespace = 'voucher')),
	path('', include(acara, namespace = 'acara')),
	path('', include(penugasan, namespace = 'penugasan')),
    path('', include(rent, namespace = 'rent')),
    path('', include(sepeda, namespace = 'sepeda')),
    path('', include(stasiun, namespace = 'stasiun')),
	path('', include(account, namespace = 'account')),
    path('', include(transaksi, namespace = 'transaksi')),
    path('', include(laporan, namespace = 'laporan')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

acara/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import acara

app_name = 'acara'


urlpatterns = [
    path('acara/', views.acara, name='acara'),
    path('acara/list_acara/', views.list_acara, name='list_acara'),
]

account/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import register
from .views import login

app_name = 'account'


urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
]

home/urls.py
from django.urls import path, include
from django.contrib.auth import views
from .views import home
from django.conf import settings

app_name = 'home'

urlpatterns = [
 path('', home, name='home'),
]

sepeda/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import sepeda

app_name = 'sepeda'


urlpatterns = [
    path('sepeda/', views.sepeda, name='sepeda'),
    path('sepeda/list_sepeda/', views.list_sepeda, name='list_sepeda'),
    path('sepeda/post_sepeda/',views.post_sepeda, name = 'post_sepeda'),
    path('sepeda/delete_sepeda/',views.delete_sepeda, name = 'delete_sepeda'),
    path('sepeda/list_sepeda/modal_update_sepeda',views.modal_update_sepeda, name = 'modal_update_sepeda'),
    path('sepeda/list_sepeda/modal_update_sepeda/update_sepeda',views.update_sepeda, name = 'update_sepeda'),
]

stasiun/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = 'stasiun'


urlpatterns = [
    path('stasiun/', views.stasiun, name='stasiun'),
    path('stasiun/list_stasiun/', views.list_stasiun, name='list_stasiun'),
    path('stasiun/post_stasiun/', views.post_stasiun, name = 'post_stasiun'),
    path('stasiun/delete_stasiun/',views.delete_stasiun, name = 'delete_stasiun'),
    path('stasiun/list_stasiun/modal_update_stasiun',views.modal_update_stasiun, name = 'modal_update_stasiun'),
    path('stasiun/list_stasiun/modal_update_stasiun/update_stasiun',views.update_stasiun, name = 'update_stasiun'),
]

transaksi/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = 'transaksi'


urlpatterns = [
    path('transaksi/', views.transaksi, name='transaksi'),
	path('topup/', views.topup, name = 'topup'),
	path('transaksi/topup/', views.topup_act, name = 'topup_act'),
]

transaksi/models.py
from django.db import models

# Create your models here.

transaksi/views.py
from django.shortcuts import render
from django.urls import reverse
from django.db import connection
from django.contrib import messages
from django.http import HttpResponseRedirect

# Create your views here.

def transaksi(request):
	response = {}
	cursor = connection.cursor()
	cursor.execute('set search_path to bike_sharing')
	cursor.execute("SELECT tr.date_time, tr.jenis, tr.nominal FROM transaksi as tr, anggota as a, person as p WHERE a.ktp = p.ktp and tr.no_kartu_anggota = a.no_kartu;")
	retrieve = cursor.fetchall()
	response['transaksi'] = retrieve
	print(response)
	return render(request, 'transaksi.html', response)
	
def topup(request):
	return render (request, 'topup.html')
	
def topup_act(request):
	response = {}
	cursor.execute('set search_path to bike_sharing')
	if(request.method == "POST"):
		saldo_topup = request.POST['topup']
		cursor.execute("SELECT a.saldo FROM anggota as a WHERE a.ktp = '"+ktp+"' ")
		saldo = cursor.fetchall()
		for i in saldo:
			saldo = i[0]
		saldo_new = int(saldo_topup) + int(saldo)
		cursor.execute("UPDATE anggota SET saldo = '"+ str(saldo_akhir) +"' WHERE a.ktp = '"+ktp+"' ")
		return HttpResponseRedirect('/transaksi/topup')
	else:
		messages.error(request, "Top up transaction cant be done")
		return HttpResponseRedirect('/transaksi/')
		
def topup_list(request):
	response = {}
	cursor = connection.cursor()
	cursor.execute('set search_path to bike_sharing')
	cursor.execute("SELECT tr.date_time, tr.jenis, tr.nominal FROM transaksi as tr, anggota as a, person as p WHERE a.ktp = p.ktp and tr.no_kartu_anggota = a.no_kartu;")
	retrieve = cursor.fetchall()
	response['transaksi'] = retrieve
	print(response)
	return render(request, 'topup.html', response)

transaksi/templates/topup.html
{% load staticfiles %}
{% load static %}	
{% block content %}

	<!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Favicon-->
		<link rel="shortcut icon" href="{% static 'fav.png' %}">
		<!-- Author Meta -->
		<meta name="author" content="codepixer">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->
		<title>Car Rentals</title>

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet"> 
			<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="{% static 'css/linearicons.css' %}" type = 
			text/css">
			<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
			<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
			<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">					
			<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
			<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">			
			<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
			<link rel="stylesheet" href="{% static 'css/main.css' %}">
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		</head>
		<body>

			  <header id="header" id="home">
			    <div class="container">
			    	<div class="row align-items-center justify-content-between d-flex">
				      <div id="logo">
				        <a href="{% url 'home:home' %}"><img src="{% static 'img/bikesharing-logo.png' %}" style="width: 50px; height: 50px;object-fit: contain;"/></a>
				      </div>
				      <nav id="nav-menu-container">
				        <ul class="nav-menu">
				          <li class="menu-active"><a href="{% url 'home:home' %}">Home</a></li>
				          <li><a href="{% url 'rent:rent' %}">Rent</a></li>
				          <li><a href="{% url 'voucher:voucher' %}">Voucher</a></li>
						  <li><a href="{% url 'penugasan:penugasan' %}">Assignment</a></li>
						  <li><a href="{% url 'acara:acara' %}">Event</a></li>
				          <li><a href="{% url 'stasiun:stasiun' %}">Station</a></li>	
				          <li><a href="{% url 'sepeda:sepeda' %}">Bike</a></li>
						  <li><a href="{% url 'account:login' %}">Log In</a></li>
						  <li><a href="{% url 'account:register' %}">Register</a></li>
				          <!-- <li class="menu-has-children"><a href="">Login</a>
				            <ul>
				              <li><a href="{% url 'transaksi:transaksi' %}">Transactions</a></li>
				              <li><a href="elements.html">Elements</a></li>
				            </ul>
				          </li> -->			          
				        </ul>
				      </nav><!-- #nav-menu-container -->		    		
			    	</div>
			    </div>
			  </header><!-- #header -->


			<!-- start banner Area -->
			<section class="banner-area relative" id="home">
				<div class="overlay overlay-bg"></div>	
				<div class="container">
					<div class="row fullscreen d-flex align-items-center justify-content-center">
						
						<div class="col-lg-5  col-md-6 header-right">
							<h4 class="text-white pb-30">Top Up</h4>
							<form class="form" role="form" autocomplete="off">		    
							    <div class="from-group">
							    	<input class="form-control txt-field" type="text" name="nominal" placeholder="Nominal">
							    </div>
							    <div class="form-group row">
							        <div class="col-md-12">
							            <button type="reset" class="btn btn-default btn-lg btn-block text-center text-uppercase">Submit</button>
							        </div>
							    </div>
							</form>
						</div>											
					</div>
				</div>					
			</section>
			<!-- End banner Area -->
			
			<!-- start footer Area -->		
			<footer class="footer-area section-gap">
				<div class="container">
					<div class="row">
						<div class="col-lg-2 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Quick links</h6>
								<ul>
									<li><a href="#">Jobs</a></li>
									<li><a href="#">Brand Assets</a></li>
									<li><a href="#">Investor Relations</a></li>
									<li><a href="#">Terms of Service</a></li>
								</ul>								
							</div>
						</div>
						<div class="col-lg-2 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Features</h6>
								<ul>
									<li><a href="#">Jobs</a></li>
									<li><a href="#">Brand Assets</a></li>
									<li><a href="#">Investor Relations</a></li>
									<li><a href="#">Terms of Service</a></li>
								</ul>								
							</div>
						</div>
						<div class="col-lg-2 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Resources</h6>
								<ul>
									<li><a href="#">Jobs</a></li>
									<li><a href="#">Brand Assets</a></li>
									<li><a href="#">Investor Relations</a></li>
									<li><a href="#">Terms of Service</a></li>
								</ul>								
							</div>
						</div>												
						<div class="col-lg-2 col-md-6 col-sm-6 social-widget">
							<div class="single-footer-widget">
								<h6>Follow Us</h6>
								<p>Let's be social</p>
								<div class="footer-social d-flex align-items-center">
									<a href="#"><i class="fa fa-facebook"></i></a>
									<a href="#"><i class="fa fa-twitter"></i></a>
									<a href="#"><i class="fa fa-dribbble"></i></a>
									<a href="#"><i class="fa fa-behance"></i></a>
								</div>
							</div>
						</div>							
						
						<p class="mt-50 mx-auto footer-text col-lg-12">
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>											
					</div>
				</div>
			</footer>	
			<!-- End footer Area -->		

			<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
			<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>			
			<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
			<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>			
  			<script src="{% static 'js/easing.min.js' %}"></script>			
			<script src="{% static 'js/hoverIntent.js' %}"></script>
			<script src="{% static 'js/superfish.min.js' %}"></script>	
			<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
			<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>	
			<script src="{% static 'js/owl.carousel.min.js' %}"></script>			
			<script src="{% static 'js/jquery.sticky.js' %}"></script>
			<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>	
			<script src="{% static 'js/waypoints.min.js' %}"></script>
			<script src="{% static 'js/jquery.counterup.min.js' %}"></script>					
			<script src="{% static 'js/parallax.min.js' %}"></script>		
			<script src="{% static 'js/mail-script.js' %}"></script>	
			<script src="{% static 'js/main.js' %}"></script>
		</body>
	</html>

{% endblock content %}

transaksi/templates/transaksi.html
{% load staticfiles %}
{% load static %}	
{% block content %}

	<!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Favicon-->
		<link rel="shortcut icon" href="{% static 'fav.png' %}">
		<!-- Author Meta -->
		<meta name="author" content="codepixer">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->
		<title>Car Rentals</title>

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet"> 
			<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="{% static 'css/linearicons.css' %}" type = 
			text/css">
			<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
			<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
			<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">					
			<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
			<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">			
			<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
			<link rel="stylesheet" href="{% static 'css/main.css' %}">
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		</head>
		<body>

			  <header id="header" id="home">
			    <div class="container">
			    	<div class="row align-items-center justify-content-between d-flex">
				      <div id="logo">
				        <a href="{% url 'home:home' %}"><img src="{% static 'img/bikesharing-logo.png' %}" style="width: 50px; height: 50px;object-fit: contain;"/></a>
				      </div>
				      <nav id="nav-menu-container">
				        <ul class="nav-menu">
				          <li class="menu-active"><a href="{% url 'home:home' %}">Home</a></li>
				          <li><a href="{% url 'rent:rent' %}">Rent</a></li>
				          <li><a href="{% url 'voucher:voucher' %}">Voucher</a></li>
						  <li><a href="{% url 'penugasan:penugasan' %}">Assignment</a></li>
						  <li><a href="{% url 'acara:acara' %}">Event</a></li>
				          <li><a href="{% url 'stasiun:stasiun' %}">Station</a></li>	
				          <li><a href="{% url 'sepeda:sepeda' %}">Bike</a></li>
						  <li><a href="{% url 'account:login' %}">Log In</a></li>
						  <li><a href="{% url 'account:register' %}">Register</a></li>
				          <!-- <li class="menu-has-children"><a href="">Login</a>
				            <ul>
				              <li><a href="{% url 'transaksi:transaksi' %}">Transactions</a></li>
				              <li><a href="elements.html">Elements</a></li>
				            </ul>
				          </li> -->			          
				        </ul>
				      </nav><!-- #nav-menu-container -->		    		
			    	</div>
			    </div>
			  </header><!-- #header -->


			<!-- start banner Area -->
			<section class="banner-area relative" id="home">
				<div class="overlay overlay-bg"></div>	
				<div class="container">
					<div class="row fullscreen d-flex align-items-center justify-content-center">											
					</div>
				</div>					
			</section>
			<!-- End banner Area -->	

			<!-- Start List Area -->
			<section class="feature-area section-gap" id="service">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-8 pb-40 header-text">
							<h1>Transaction List</h1>
						</div>
					</div>
					<div class="row">
						<a href="" class="genric-btn primary-border circle arrow center-block">Sort</a>
						<table class="table" id="vouchertable">
							  <thead>
							    <tr>
							      <th scope="col">No</th>
							      <th scope="col">Tanggal</th>
							      <th scope="col">Jenis Transaksi</th>
							      <th scope="col">Nominal</th>
							    </tr>
							  </thead>

							  <tbody>
								{% for i in transaksi %}
							    <tr>
									<th scope="row" class="counterCell"></th>
									<td>{{i.0}}</td>
									<td>{{i.1}}</td>
									<td>{{i.2}}</td>
							    </tr>
								{% endfor %}
							  </tbody>
						<ul class="pager">
					  <li class="previous"><a href="#">Previous</a></li>
					  <li class="next"><a href="#">Next</a></li>
					</ul>
						</table>
										
					</div>
				</div>	
			</section>
			<!-- End feature Area -->			
			


			<!-- start footer Area -->		
			<footer class="footer-area section-gap">
				<div class="container">
					<div class="row">
						<div class="col-lg-2 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Quick links</h6>
								<ul>
									<li><a href="#">Jobs</a></li>
									<li><a href="#">Brand Assets</a></li>
									<li><a href="#">Investor Relations</a></li>
									<li><a href="#">Terms of Service</a></li>
								</ul>								
							</div>
						</div>
						<div class="col-lg-2 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Features</h6>
								<ul>
									<li><a href="#">Jobs</a></li>
									<li><a href="#">Brand Assets</a></li>
									<li><a href="#">Investor Relations</a></li>
									<li><a href="#">Terms of Service</a></li>
								</ul>								
							</div>
						</div>
						<div class="col-lg-2 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Resources</h6>
								<ul>
									<li><a href="#">Jobs</a></li>
									<li><a href="#">Brand Assets</a></li>
									<li><a href="#">Investor Relations</a></li>
									<li><a href="#">Terms of Service</a></li>
								</ul>								
							</div>
						</div>												
						<div class="col-lg-2 col-md-6 col-sm-6 social-widget">
							<div class="single-footer-widget">
								<h6>Follow Us</h6>
								<p>Let's be social</p>
								<div class="footer-social d-flex align-items-center">
									<a href="#"><i class="fa fa-facebook"></i></a>
									<a href="#"><i class="fa fa-twitter"></i></a>
									<a href="#"><i class="fa fa-dribbble"></i></a>
									<a href="#"><i class="fa fa-behance"></i></a>
								</div>
							</div>
						</div>							
						
						<p class="mt-50 mx-auto footer-text col-lg-12">
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>											
					</div>
				</div>
			</footer>	
			<!-- End footer Area -->		

			<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
			<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>			
			<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
			<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>			
  			<script src="{% static 'js/easing.min.js' %}"></script>			
			<script src="{% static 'js/hoverIntent.js' %}"></script>
			<script src="{% static 'js/superfish.min.js' %}"></script>	
			<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
			<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>	
			<script src="{% static 'js/owl.carousel.min.js' %}"></script>			
			<script src="{% static 'js/jquery.sticky.js' %}"></script>
			<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>	
			<script src="{% static 'js/waypoints.min.js' %}"></script>
			<script src="{% static 'js/jquery.counterup.min.js' %}"></script>					
			<script src="{% static 'js/parallax.min.js' %}"></script>		
			<script src="{% static 'js/mail-script.js' %}"></script>	
			<script src="{% static 'js/main.js' %}"></script>
		</body>
	</html>

{% endblock content %}