Bike_Sharing_D4/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
import home.urls as home
import voucher.urls as voucher
import acara.urls as acara
import penugasan.urls as penugasan
import peminjaman.urls as rent
import sepeda.urls as sepeda
import stasiun.urls as stasiun

import account.urls as account
import transaksi.urls as transaksi
import laporan.urls as laporan



import transaksi.urls as transaksi
from home import views
from voucher import views
from penugasan import views
from acara import views
from peminjaman import views
from sepeda import views
from stasiun import views
from account import views
from transaksi import views
from laporan import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(home)),
    path('', include(voucher, namespace = 'voucher')),
	path('', include(acara, namespace = 'acara')),
	path('', include(penugasan, namespace = 'penugasan')),
    path('', include(rent, namespace = 'rent')),
    path('', include(sepeda, namespace = 'sepeda')),
    path('', include(stasiun, namespace = 'stasiun')),
	path('', include(account, namespace = 'account')),
    path('', include(transaksi, namespace = 'transaksi')),
    path('', include(laporan, namespace = 'laporan')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

acara/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import acara

app_name = 'acara'


urlpatterns = [
    path('acara/', views.acara, name='acara'),
    path('acara/list_acara/', views.list_acara, name='list_acara'),
]

account/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import register
from .views import login

app_name = 'account'


urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
]

home/urls.py
from django.urls import path, include
from django.contrib.auth import views
from .views import home
from django.conf import settings

app_name = 'home'

urlpatterns = [
 path('', home, name='home'),
]

laporan/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = 'laporan'


urlpatterns = [
    path('laporan/', views.laporan, name='laporan'),
]

sepeda/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from .views import sepeda

app_name = 'sepeda'


urlpatterns = [
    path('sepeda/', views.sepeda, name='sepeda'),
    path('sepeda/list_sepeda/', views.list_sepeda, name='list_sepeda'),
    path('sepeda/post_sepeda/',views.post_sepeda, name = 'post_sepeda'),
    path('sepeda/delete_sepeda/',views.delete_sepeda, name = 'delete_sepeda'),
    path('sepeda/list_sepeda/modal_update_sepeda',views.modal_update_sepeda, name = 'modal_update_sepeda'),
    path('sepeda/list_sepeda/modal_update_sepeda/update_sepeda',views.update_sepeda, name = 'update_sepeda'),
]

stasiun/urls.py
from django.urls import path
from django.conf.urls import url
from . import views


app_name = 'stasiun'


urlpatterns = [
    path('stasiun/', views.stasiun, name='stasiun'),
    path('stasiun/list_stasiun/', views.list_stasiun, name='list_stasiun'),
    path('stasiun/post_stasiun/', views.post_stasiun, name = 'post_stasiun'),
    path('stasiun/delete_stasiun/',views.delete_stasiun, name = 'delete_stasiun'),
    path('stasiun/list_stasiun/modal_update_stasiun',views.modal_update_stasiun, name = 'modal_update_stasiun'),
    path('stasiun/list_stasiun/modal_update_stasiun/update_stasiun',views.update_stasiun, name = 'update_stasiun'),
]

sepeda/models.py
from django.db import models

# Create your models here.

sepeda/views.py
from django.shortcuts import render
from django.db import connection
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from django.urls import reverse
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt


# Create your views here.
def sepeda(request):
    cursor = connection.cursor()
    cursor.execute('set search_path to bike_sharing,public')
    cursor.execute("SELECT P.nama FROM ANGGOTA as A, PERSON as P WHERE A.ktp = P.ktp;")
    data = cursor.fetchall()

    response = {}
    response ['namapenyumbang'] = data
    print(response)

    cursor.execute("SELECT nama FROM STASIUN;")
    data1 = cursor.fetchall()
    response ['namastasiun'] = data1
    print(response)

    return render(request, 'sepeda.html', response)

def list_sepeda(request):
    cursor = connection.cursor()
    cursor.execute('SELECT Se.nomor,Se.merk,Se.jenis,status,Se.id_stasiun,Se.no_kartu_penyumbang FROM BIKE_SHARING.SEPEDA Se, BIKE_SHARING.STASIUN St, BIKE_SHARING.ANGGOTA a WHERE a.no_kartu = Se.no_kartu_penyumbang AND Se.id_stasiun = St.id_stasiun;')
    res = cursor.fetchall()
    response = {}
    response['sepeda'] = res
    return render(request, 'list_sepeda.html', response)

def post_sepeda(request):
    if(request.method=="POST"):
          
        merk = request.POST['merk']
        jenis = request.POST['jenis']
        status = request.POST['status']
        stasiun = request.POST['stasiun']
        penyumbang = request.POST['penyumbang']
      
        statusNow = False
        if(str(status)=='Tersedia'):
            statusNow = True
        else:
            statusNow = False

        cursor = connection.cursor()
        cursor.execute('SET SEARCH_PATH to BIKE_SHARING,public')
        cursor.execute("select a.no_kartu from anggota as a, person as p where p.nama='"+penyumbang+"' and p.ktp = a.ktp;") 
        res_penyumbang = cursor.fetchone()
        no_kartu_penyumbang = res_penyumbang[0]
        
        cursor.execute('SET SEARCH_PATH to BIKE_SHARING,public')
        cursor.execute("SELECT id_stasiun FROM STASIUN WHERE nama='"+stasiun+"';")
        res_stasiun = cursor.fetchone()
        id_stasiun = res_stasiun[0]
    

        cursor.execute("select nomor from sepeda order by cast (nomor as int) desc;")
        res_sepeda = cursor.fetchone()
        nomor = int(res_sepeda[0]) +1

        cursor.execute("INSERT INTO sepeda(nomor,merk,jenis,status,id_stasiun,no_kartu_penyumbang) values("+"'"+str(nomor)+"','" +str(merk)+"','" + str(jenis) +"','" + str(statusNow) +"', '" + str(id_stasiun) +"', '" + str(no_kartu_penyumbang) +"' );")
        messages.error(request, "success")
        return HttpResponseRedirect('/sepeda/list_sepeda')

    else:
        messages.error(request, "gagal")
        return HttpResponseRedirect('/sepeda/sepeda')

@csrf_exempt
def delete_sepeda(request):
    if(request.method=="POST"):
        nomor= request.POST['id']
        cursor = connection.cursor()
        cursor.execute('set search_path to bike_sharing,public')
        cursor.execute("delete from sepeda where nomor='"+nomor+"';")
        messages.error(request, "success")
        return HttpResponseRedirect('/sepeda/list_sepeda')
    else:
        messages.error(request, "gagal")
        return HttpResponseRedirect('/sepeda/list_sepeda')

@csrf_exempt
def modal_update_sepeda(request):
    if(request.method=="POST"):
        response={}
        sepeda= request.POST['id']
        cursor = connection.cursor()
        cursor.execute('set search_path to bike_sharing,public')
        cursor.execute("select * from sepeda where nomor='"+sepeda+"';")
        stasiun = cursor.fetchone()
     
        cursor.execute("select s.nama from stasiun as s, sepeda as a where a.nomor ='"+sepeda+"' and a.id_stasiun = s.id_stasiun;")
        nama_stasiun = cursor.fetchone()
        
        cursor.execute("select p.nama from person as p, anggota as a, sepeda as n where n.nomor='"+sepeda+"' and a.no_kartu=n.no_kartu_penyumbang and p.ktp=a.ktp;")
        res_penyumbang = cursor.fetchone()
        nama_penyumbang = res_penyumbang[0]

        cursor.execute("select jenis from sepeda where nomor='"+sepeda+"';")
        jenis = cursor.fetchone()

        cursor.execute("select status from sepeda where nomor='"+sepeda+"';")
        status = cursor.fetchone()

        cursor.execute("select merk from sepeda where nomor='"+sepeda+"';")
        merk = cursor.fetchone()

        cursor.execute("select p.nama from person as p, anggota as a where a.ktp=p.ktp")
        penyumbang = cursor.fetchall()

        cursor.execute("select nama from stasiun")
        stasiun = cursor.fetchall()

        response['stasiun'] = stasiun
        response['penyumbang'] = penyumbang
        response['sepeda'] = sepeda
        response['nama_stasiun'] = nama_stasiun
        response['nama_penyumbang'] = nama_penyumbang
        response['jenis'] = jenis[0]
        response['merk'] = merk[0]
        response['status'] = status[0]

        messages.error(request, "success")
        return JsonResponse(response)

    else:
        messages.error(request, "gagal")
        return HttpResponseRedirect('/sepeda/list_sepeda')

@csrf_exempt
def update_sepeda(request):
    if(request.method=="POST"):
        merk = request.POST['merk']    
        jenis = request.POST['jenis']
        status = request.POST['status']
        stasiun = request.POST['stasiun']
        penyumbang = request.POST['penyumbang']
        nomor = request.POST['nomor']

        current_status = False
        if(str(status)=='Tersedia'):
          current_status = True
        else:
          current_status = False

        cursor = connection.cursor()
        cursor.execute('set search_path to bike_sharing,public')

        cursor.execute("select a.no_kartu from anggota as a, person as p where p.nama='"+penyumbang+"' and p.ktp = a.ktp")
        hasil = cursor.fetchone()
        no_kartu = hasil[0]

        cursor.execute("update sepeda set merk='"+merk+"', jenis='"+jenis+"', status='"+str(current_status)+"', no_kartu_penyumbang='"+no_kartu+"' where nomor = '"+str(nomor)+"';")
    
        messages.error(request, "success")
        return HttpResponseRedirect('/sepeda/list_sepeda')
    else:
        messages.error(request, "gagal")
        return HttpResponseRedirect('/sepeda/list_sepeda')



       

sepeda/templates/sepeda.html
{% load staticfiles %}
{% load static %}	
{% block content %}

	<!DOCTYPE html>
	<html lang="zxx" class="no-js">
	<head>
		<!-- Mobile Specific Meta -->
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<!-- Favicon-->
		<link rel="shortcut icon" href="{% static 'fav.png' %}">
		<!-- Author Meta -->
		<meta name="author" content="codepixer">
		<!-- Meta Description -->
		<meta name="description" content="">
		<!-- Meta Keyword -->
		<meta name="keywords" content="">
		<!-- meta character set -->
		<meta charset="UTF-8">
		<!-- Site Title -->
		<title>Car Rentals</title>

		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet"> 
			<!--
			CSS
			============================================= -->
			<link rel="stylesheet" href="{% static 'css/linearicons.css' %}" type = 
			"text/css">
			<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
			<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
			<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
			<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">					
			<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
			<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">			
			<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
			<link rel="stylesheet" href="{% static 'css/main.css' %}">
			<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
			<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
		</head>
		<body>

				<header id="header" id="home">
						<div class="container">
							<div class="row align-items-center justify-content-between d-flex">
								<div id="logo">
									<a href="#"><img src="{% static 'img/bikesharing-logo.png' %}" style="width: 50px; height: 50px;object-fit: contain;" /></a>
								</div>
								<nav id="nav-menu-container">
									<ul class="nav-menu">
										<li class="menu-active"><a href="#">Home</a></li>
										<li class="menu-has-children"><a href="{% url 'rent:list_rent' %}">Rent</a>
								<ul>
									<li><a href="{% url 'rent:rent' %}">Create Rent</a></li>
									<li><a href="{% url 'rent:list_rent' %}">List of Rents</a></li>
									
								</ul>
								</li>
										<li class="menu-has-children"><a href="{% url 'voucher:voucher' %}">Voucher</a>
								<ul>
									<li><a href="{% url 'voucher:form_voucher' %}">Create Voucher</a></li>
									<li><a href="{% url 'voucher:voucher' %}">List of Vouchers</a></li>
									
								</ul>
								</li>	
								<li class="menu-has-children"><a href="{% url 'penugasan:list_penugasan' %}">Assignment</a>
									<ul>
										<li><a href="{% url 'penugasan:penugasan' %}">Create Assignment</a></li>
										<li><a href="{% url 'penugasan:list_penugasan' %}">List of Assignments</a></li>
										
									</ul>
									</li>
								<li class="menu-has-children"><a href="{% url 'acara:list_acara' %}">Event</a>
								<ul>
									<li><a href="{% url 'acara:acara' %}">Create Event</a></li>
									<li><a href="{% url 'acara:list_acara' %}">List of Events</a></li>
									
								</ul>
							</li>	
	
								<li class="menu-has-children"><a href="{% url 'stasiun:list_stasiun' %}">Station</a>
								<ul>
									<li><a href="{% url 'stasiun:stasiun' %}">Create Station</a></li>
									<li><a href="{% url 'stasiun:list_stasiun' %}">List of Stations</a></li>
									
								</ul>
							</li>	
	
							<li class="menu-has-children"><a href="{% url 'sepeda:list_sepeda' %}">Bike</a>
								<ul>
									<li><a href="{% url 'sepeda:sepeda' %}">Create Bike</a></li>
									<li><a href="{% url 'sepeda:list_sepeda' %}">List of Bikes</a></li>
									
								</ul>
							</li>	
							 
								
										<li class="menu-has-children"><a href="{% url 'account:login' %}">Log In</a>
											<ul>
												<li><a href="{% url 'account:register' %}">Register</a></li>
									<li><a href="{% url 'transaksi:transaksi' %}">Transaction</a></li>
									<li><a href="{% url 'laporan:laporan' %}">Reports</a></li>
											</ul>
										</li>			          
									</ul>
								</nav><!-- #nav-menu-container -->		    		
							</div>
						</div>
					</header><!-- #header -->


			<!-- start banner Area -->
			<section class="banner-area relative" id="home">
				<div class="overlay overlay-bg"></div>	
				<div class="container">
					<div class="row fullscreen d-flex align-items-center justify-content-center">
						
						<div class="col-lg-5  col-md-6 header-right">
							<h4 class="text-white pb-30">Create Sepeda</h4>
							<!-- <form class="form" role="form" autocomplete="off">	 -->
									<form action="/sepeda/post_sepeda/" method="POST">
										{% csrf_token %}
										<form>    
							    <div class="from-group">

									<input class="form-control txt-field" type="text" name="merk" placeholder="Merk" required>

									<input class="form-control txt-field" type="text" name="jenis" placeholder="Jenis" required>
										
									<div class="form-group">
										<div class="default-select" id="default-select">
											<select name="status" class="form-control" placeholder="Status" required>
												<option value="" disabled selected hidden>Pilih Status</option>
												<option>Tersedia</option>
												<option>Tidak Tersedia</option>
                                                
											</select>
										</div>
									</div>

									<div class="form-group">
										<div class="default-select" id="default-select">
											<select name="stasiun" class="form-control" placeholder="Stasiun" required>
												<option value="" disabled selected hidden>Pilih Stasiun</option>
												{% for i in namastasiun %}
                            <option>{{i.0}}</option>
                           
                          {% endfor %}
											</select>
										</div>
                                    </div>
																		
																		
                                    <div class="form-group">
										<div class="default-select" id="default-select">
											<select name="penyumbang" class="form-control" placeholder="Penyumbang" required>
												<option value="" disabled selected hidden>Pilih Penyumbang</option>
												{% for i in namapenyumbang %}
												<option>{{i.0}}</option>
											 
											{% endfor %}
											</select>
										</div>
									</div>
									</div>
									
							    <div class="form-group row">
							        <div class="col-md-12">
							            <button type="submit" class="btn btn-default btn-lg btn-block text-center text-uppercase">Submit</button>
							        </div>
							    </div>
							</form>
						</div>											
					</div>
				</div>					
			</section>
			<!-- End banner Area -->	

			<!-- Start List Area -->
			
			


			<!-- start footer Area -->		
			<footer class="footer-area section-gap">
				<div class="container">
					<div class="row">
						<div class="col-lg-2 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Quick links</h6>
								<ul>
									<li><a href="#">Jobs</a></li>
									<li><a href="#">Brand Assets</a></li>
									<li><a href="#">Investor Relations</a></li>
									<li><a href="#">Terms of Service</a></li>
								</ul>								
							</div>
						</div>
						<div class="col-lg-2 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Features</h6>
								<ul>
									<li><a href="#">Jobs</a></li>
									<li><a href="#">Brand Assets</a></li>
									<li><a href="#">Investor Relations</a></li>
									<li><a href="#">Terms of Service</a></li>
								</ul>								
							</div>
						</div>
						<div class="col-lg-2 col-md-6 col-sm-6">
							<div class="single-footer-widget">
								<h6>Resources</h6>
								<ul>
									<li><a href="#">Jobs</a></li>
									<li><a href="#">Brand Assets</a></li>
									<li><a href="#">Investor Relations</a></li>
									<li><a href="#">Terms of Service</a></li>
								</ul>								
							</div>
						</div>												
						<div class="col-lg-2 col-md-6 col-sm-6 social-widget">
							<div class="single-footer-widget">
								<h6>Follow Us</h6>
								<p>Let's be social</p>
								<div class="footer-social d-flex align-items-center">
									<a href="#"><i class="fa fa-facebook"></i></a>
									<a href="#"><i class="fa fa-twitter"></i></a>
									<a href="#"><i class="fa fa-dribbble"></i></a>
									<a href="#"><i class="fa fa-behance"></i></a>
								</div>
							</div>
						</div>							
						
						<p class="mt-50 mx-auto footer-text col-lg-12">
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>											
					</div>
				</div>
			</footer>	
			<!-- End footer Area -->		

			<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
			<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
			<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>			
			<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
			<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>			
  			<script src="{% static 'js/easing.min.js' %}"></script>			
			<script src="{% static 'js/hoverIntent.js' %}"></script>
			<script src="{% static 'js/superfish.min.js' %}"></script>	
			<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
			<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>	
			<script src="{% static 'js/owl.carousel.min.js' %}"></script>			
			<script src="{% static 'js/jquery.sticky.js' %}"></script>
			<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>	
			<script src="{% static 'js/waypoints.min.js' %}"></script>
			<script src="{% static 'js/jquery.counterup.min.js' %}"></script>					
			<script src="{% static 'js/parallax.min.js' %}"></script>		
			<script src="{% static 'js/mail-script.js' %}"></script>	
			<script src="{% static 'js/main.js' %}"></script>
		
		</body>
	</html>

{% endblock content %}